stages:
  - test
  - build

.common:
  image: node:16.9-alpine
  before_script:
    - npm set-script prepare ""
    - npm ci --cache .npm --prefer-offline
  cache:
    key: npm
    paths:
      - .npm/

test:
  extends: .common
  stage: test
  script:
    - npm run tsc
    - npm run test

build:
  extends: .common
  stage: build
  variables:
    NODE_ENV: "production"
  script:
    - npm run build
